name: CI # ビルド と 単体テスト を実行する。

# どのイベントをトリガーにしてワークフローを実行するかを指定
# トリガー: `develop` への push、および全ての Pull Request
# マークダウンファイル もしくは docs ディレクトリ内のファイルの変更によるワークフローは実行しない
on:
  push:
    branches: [develop]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'

# GITHUB_TOKEN を最小権限（リポジトリの読み取りのみ）に絞る
permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      # Gradle のキャッシュ。これがないと毎回 Gradle 本体と依存ライブラリをインストールするため、ビルドの時間がかかる。
      - uses: gradle/actions/setup-gradle@v4

      - name: Check Java version
        run: java --version

      # 実行権限を付与
      - name: Grant execute permission for gradle
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew build

      # SpotBugs の実行
      - name: Execute  SpotBugs
        run: ./gradlew spotbugsMain
